name: Build

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup credentails
        run: |
          cp ./HINClient/MLHINClientCredential.sample.h ./HINClient/MLHINClientCredential.h
          cp ./Medidata/MedidataCredential.sample.h ./Medidata/MedidataCredential.h
      - name: Download databases
        run: |
          cd AmiKoOSX
          curl -o amiko_report_de.html http://pillbox.oddb.org/amiko_report_de.html
          curl -o amiko_db_full_idx_de.zip http://pillbox.oddb.org/amiko_db_full_idx_de.zip
          curl -o amiko_frequency_de.db.zip http://pillbox.oddb.org/amiko_frequency_de.db.zip
          curl -o drug_interactions_csv_de.zip http://pillbox.oddb.org/drug_interactions_csv_de.zip
          curl -o amiko_report_fr.html http://pillbox.oddb.org/amiko_report_fr.html
          curl -o amiko_db_full_idx_fr.zip http://pillbox.oddb.org/amiko_db_full_idx_fr.zip
          curl -o amiko_frequency_fr.db.zip http://pillbox.oddb.org/amiko_frequency_fr.db.zip
          curl -o drug_interactions_csv_fr.zip http://pillbox.oddb.org/drug_interactions_csv_fr.zip
          unzip amiko_db_full_idx_de.zip
          unzip amiko_frequency_de.db.zip
          unzip drug_interactions_csv_de.zip
          unzip amiko_db_full_idx_fr.zip
          unzip amiko_frequency_fr.db.zip
          unzip drug_interactions_csv_fr.zip
          rm amiko_db_full_idx_de.zip amiko_frequency_de.db.zip drug_interactions_csv_de.zip amiko_db_full_idx_fr.zip amiko_frequency_fr.db.zip drug_interactions_csv_fr.zip
      - name: Build
        run: |
          xcodebuild clean build -allowProvisioningUpdates -project AmiKo.xcodeproj -scheme AmiKo CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
          xcodebuild clean build -allowProvisioningUpdates -project AmiKo.xcodeproj -scheme CoMed CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
